### ISSUE TITLE
Issue with hello world decompilation

### ISSUE THREAD

**Issue by sdasgup3** [repzret/dagger#1]
With a program like
```C
#include<stdio.h>
int main(int argc, char* argv[]) {
  printf("Hello WOrld!\n");
  return 0;
}
```

```
clang -m64 hello.c -o hello
./build/bin/llvm-dec ./hello
```
Gives:
```
  <MCInst 939>
Cannot translate instruction: 
  <MCInst 939>
Cannot translate instruction: 
  <MCInst 939>
Cannot translate instruction: 
  <MCInst 939>
Cannot translate instruction: 
  <MCInst 939>
Cannot translate instruction:
```
But if compiled with 
`clang -m64 hello.c -c -o hello`
It correctly decompiles to IR. But the IR does not seem functional? Is the external function printf identified?

**Comment by liangdzou** [comment]
The problem is still there...

**Comment by repzret** [comment]
c7f0d62 and 860e271 should take care of this;  give it another try and let me know how it goes!

The issue was that the glibc entrypoint code (_start and friends) contains 'hlt', which should be unreachable.  Additionally, it has 'rep;ret' which is an optimized alternative to 'ret'.

> The problem is still there...

Patches always welcome ;)
